# Generated by Django 3.2.4 on 2021-06-28 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0002_customermoder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModer',
            new_name='CustomerModel',
        ),
    ]
