# Generated by Django 3.2.4 on 2021-06-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210628_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='pincode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_category',
            field=models.CharField(choices=[('M', 'MOBILE'), ('C', 'CLOTHES'), ('H', 'HOME'), ('E', 'ELECTRONIC')], max_length=10),
        ),
    ]
