# Generated by Django 3.2.4 on 2021-06-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('shop', '0005_auto_20210628_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='seller',
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
        migrations.DeleteModel(
            name='SellerModel',
        ),
    ]
