# Generated by Django 3.2.4 on 2021-07-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210628_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='default_address',
            field=models.BooleanField(blank=True, default=True, verbose_name='Make it default Address'),
            preserve_default=False,
        ),
    ]
