# Generated by Django 3.2.4 on 2021-07-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_addressmodel_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
